### PR TITLE
Fixed a spelling error (teh) and added a step 0 for the build procedure.

### PR DESCRIPTION
**Pull request by steelewool**

### CODE REVIEW

**Comment by olebole** [comment]
At least I didn't run into the need of using C-shell yet. Could you bring the specific error and how to reproduce it?
For ncompress, why isn't gzip enough? It also comes with an `uncompress` command. And there are no relevant `*.Z` files in the source code.
The text 
>Step 0 added by Rob & Zach Steele of SteeleWoolSoftware.

in the patch is also unneeded -- for the user it is irrelevant who you are and what your company is. Logging ("added by") is done in the git log. You should also not write
> These were required on our linux systems [...]

because the `README.install` is not a collection of experiences but instructions to the user.

Summarized, I would recommend you to close this PR yourself or to squash it to fix just the spelling error (you can edit the commit in the branch locally and then do a `push --force`).

**Comment by olebole** [comment]
At the end, I came to a need for C-shell (`mklibs`), but converted them all to `/bin/sh`(see #38).

**Comment by RobSteele49** [comment]
My point was that the files invoked during the install/make process use both csh and compress.As indicated by line 1 on some that read "#!/bin/csh" and with other the utility "compress" is called. Since I'm running on a ubuntu system I needed to install these packages. There are actually others that Joseph have identified. Without having these packages installed steps 1-3 will not work.

Would you recommend that I not have a step 0 here but rather have a different location for system dependencies. If so where would you recommend?

Also, change fixing a misspelling that I found glaring is not really very critical to fixing the make process. But, I think misspelling make a project look sloppy which is why I wanted to recommend fixing the 'teh'.

I'll let iraf let me know which he would accept for a PR.

**Comment by olebole** [comment]
Which files do you mean specifically? And where is a compress called that can't be replaced by gzip?

For the misspelling, I agree with you (that's why I wrote that you may reduce this PR just to that).

**Comment by RobSteele49** [comment]
I just did a grep to find some offending mk* files using csh. The same for compress. I would rather neither be used. At any rate, for now I'll do a PR that only fixes the spelling error and leave the other matters for future PRs.

**Comment by olebole** [comment]
You should actually combine them into one, to make the IRAF changelog better readable.

**Comment by RobSteele49** [comment]
I'd like to just delete this pull request - but I'm not sure how. Maybe @iraf can help out with that. Or anyone can let me know how. (Sorry about being new to some aspects of git.)

**Comment by olebole** [comment]
Just hit the "Close" button below, then the "Delete Branch" button, and finally to a `git branch -D updateReadme` locally. But a spelling error is a spelling error, why would you not want to get it fixed?

**Comment by steelewool** [comment]
I'll resubmit just the spelling correction.

On May 8, 2017, at 8:03 AM, Ole Streicher <notifications@github.com> wrote:

Just hit the "Close" button below, then the "Delete Branch" button, and finally to a git branch -D updateReadme locally. But a spelling error is a spelling error, why would you not want to get it fixed?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/iraf/iraf-v216","title":"iraf/iraf-v216","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/iraf/iraf-v216">https://github.com/iraf/iraf-v216</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@olebole in #5: Just hit the \"Close\" button below, then the \"Delete Branch\" button, and finally to a `git branch -D updateReadme` locally. But a spelling error is a spelling error, why would you not want to get it fixed?"}],"action":{"name":"View Pull Request","url":"<a href="https://github.com/iraf/iraf-v216/pull/5#issuecomment-299892300">https://github.com/iraf/iraf-v216/pull/5#issuecomment-299892300</a>"}}}

**Pull request closed without merging**
